using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// コア運搬表示だけを確認するための仮入力。
/// 本実装で取得・通信処理ができたら、このコンポーネントは外す。
/// </summary>
public sealed class CoreCarryDebugInput : MonoBehaviour
{
    [SerializeField] private CoreCarryController carryController;
    [SerializeField] private GameObject testCore;
    [SerializeField] private float releaseDistance = 1.2f;

    [Header("自動テスト用")]
    [SerializeField] private bool createCoreAutomatically = true;
    [SerializeField, Min(0.1f)] private float generatedCoreSize = 0.45f;

    private PlayerController playerController;

    private void Awake()
    {
        if (carryController == null)
        {
            carryController = GetComponent<CoreCarryController>();
        }

        playerController = GetComponent<PlayerController>();
    }

    private void Update()
    {
        // 同じPrefabから生成されるリモートプレイヤーは入力を受け付けない。
        if (playerController != null && !playerController.isLocalPlayer) return;
        if (Keyboard.current == null || !Keyboard.current.cKey.wasPressedThisFrame) return;
        if (carryController == null) return;

        if (carryController.IsCarrying)
        {
            Vector3 releasePosition = transform.position + transform.forward * releaseDistance;
            carryController.ReleaseCore(releasePosition);
        }
        else
        {
            if (testCore == null && createCoreAutomatically)
            {
                testCore = CreateTestCore();
            }

            if (testCore == null) return;
            carryController.BeginCarry(testCore);
        }
    }

    private GameObject CreateTestCore()
    {
        GameObject core = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        core.name = "TestCore_AutoGenerated";
        core.transform.position = transform.position + transform.forward * releaseDistance;
        core.transform.localScale = Vector3.one * generatedCoreSize;

        Rigidbody coreRigidbody = core.AddComponent<Rigidbody>();
        coreRigidbody.useGravity = true;

        Renderer coreRenderer = core.GetComponent<Renderer>();
        if (coreRenderer != null)
        {
            coreRenderer.material.color = new Color(0.1f, 0.85f, 1f);
        }

        Debug.Log("[CoreCarryDebug] テスト用コアを自動生成しました。もう一度Cで地面へ置けます。");
        return core;
    }
}
